# PostgreSQL. Ensure the pg gem is installed in your Gemfile
# gem 'pg', '~> 1.2'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: malik       # Replace with the PostgreSQL user you created
  password: password       # Replace with the PostgreSQL password you created
  host: localhost

development:
  <<: *default
  database: ecomm_development   # This can be the name of your development database

test:
  <<: *default
  database: ecomm_test          # This can be the name of your test database

production:
  <<: *default
  database: ecomm_production    # Ensure you set the environment variables for production
  username: ecomm
  password: <%= ENV['ECOMM_DATABASE_PASSWORD'] %>
